#!/usr/bin/env bash

cd game

printf '
;(function(){
' > game.js.big

fay Game.hs --strict Game -o game.js.meat
cat game.js.meat >> game.js.big
rm game.js.meat

printf '
  Strict.Game.game.step = (function(){
    var step = Strict.Game.game.step;
    return function (inps,state) {
      var inpsList = [];
      for (var k in inps) inpsList.push ([k,inps[k]]);
      return step(inpsList,state);
    }
  })();
  if (typeof module !== "undefined") {
    module.exports = Strict.Game.game;
  } else {
    window.game = Strict.Game.game;
  }
})();
' >> game.js.big

jsmin game.js.big > ../www/game.js
rm game.js.big

